# [Array Creation](https://numpy.org/doc/stable/user/basics.creation.html)

## 1 - Converting Python sequences to Numpy Arrays

In [2]:
# any array object is called an ndarray
import numpy as np

In [4]:
a1d = np.array([1, 2, 3, 4])
a2d = np.array([[1, 2], 
                [3, 4]])
a3d = np.array([
                [[1, 2], [3, 4]],
                [[5, 6], [7, 8]]
            ])

print(a1d)
print()
print(a2d)
print()
print(a3d)

[1 2 3 4]

[[1 2]
 [3 4]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# be carefull with the type of the data
a = np.array([127, 128, 129], dtype=np.int8)
a

array([ 127, -128, -127], dtype=int8)

In [6]:
a.dtype
# If you expect your integer arrays to be a specific type,
# then you need to specify the dtype while you create the array

dtype('int8')

## 2 - Intrinsic NumPy array creation functions

### 1D array creation functions

In [8]:
# numpy.arange creates arrays with regularly incrementing values
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
np.arange(2, 3, 0.1) # start, stop (not included), step

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [11]:
# numpy.linspace will create arrays with a specified number of elements, 
# and spaced equally between the specified beginning and end values
np.linspace(1., 4., 6) # start, stop, number_of_points

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

### 2D array creation functions

        numpy.eye, numpy.diag, numpy.vander

In [13]:
# np.eye(n, m) defines a 2D identity matrix. The elements where i=j are 1 and the rest are 0
np.eye(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [15]:
# numpy.diag can define either a square 2D array with given values along the diagonal 
# or if given a 2D array returns a 1D array that is only the diagonal elements
np.diag([1, 3, 5])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [16]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [17]:
np.diag([1, 2, 3], -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [18]:
a = np.array([[1, 2], [3, 4]])

In [19]:
a

array([[1, 2],
       [3, 4]])

In [20]:
np.diag(a)

array([1, 4])

In [21]:
# vander(x, n) defines a Vandermonde matrix as a 2D NumPy array
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [22]:
np.vander(np.linspace(0, 2, 5), 2)
# Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple, 
# x where the highest polynomial order is n-1

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [23]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [24]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [26]:
np.vander((1, 2, 3), 3)
# returns in the first column: [1^(3-1), 2^(3-1), 3^(3-1)] 
#               second column: [1^1, 2^1, 3^1]
#                third column: [1^0, 2^0, 3^0]

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

### General ndarray creation functions

        numpy.ones, numpy.zeros, random

In [27]:
# numpy.zeros will create an array filled with 0 values with the specified shape
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [29]:
# numpy.ones will create an array filled with 1 values
np.ones((4, 9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
# random will create an array filled with random values between 0 and 1
from numpy.random import default_rng

default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [32]:
np.random.random((3, 5))

array([[0.13645534, 0.74392949, 0.68042031, 0.67792147, 0.81604644],
       [0.03593675, 0.19660886, 0.08637919, 0.80295539, 0.6918133 ],
       [0.74825621, 0.23323336, 0.74781047, 0.90571438, 0.80999903]])

In [33]:
# numpy.indices will create a set of arrays (stacked as a one-higher dimensioned array), 
# one per dimension with each representing variation in that dimension
np.indices((2, 3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

## 3 - Replicating, joining, or mutating existing arrays

In [34]:
a = np.array([i for i in range(1, 7)])

In [35]:
a

array([1, 2, 3, 4, 5, 6])

In [37]:
b = a[: 2]
b += 1
a, b
# If you want to create a new array, use the numpy.copy array creation routine 

(array([2, 3, 3, 4, 5, 6]), array([2, 3]))

In [38]:
a = np.array([i for i in range(1, 7)])
b = a[: 2].copy()

b += 1
a, b

(array([1, 2, 3, 4, 5, 6]), array([2, 3]))

In [40]:
A = np.ones((2, 2))
A

array([[1., 1.],
       [1., 1.]])

In [41]:
B = np.eye(2, 2)
B

array([[1., 0.],
       [0., 1.]])

In [43]:
C = np.zeros((2, 2))
C

array([[0., 0.],
       [0., 0.]])

In [44]:
D = np.diag((-3, -4))
D

array([[-3,  0],
       [ 0, -4]])

In [46]:
np.block([
          [A, B],
          [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

## 4 - Reading arrays from disk, either from standard or custom formats

NumPy has two standard routines for importing a file with delimited data numpy.loadtxt and numpy.genfromtxt. 

In [47]:
np.loadtxt('simple.csv', delimiter = ',', skiprows = 1) 

array([[0., 0.],
       [1., 1.],
       [2., 4.],
       [3., 9.]])

## 5 - Creating arrays from raw bytes through the use of strings or buffers

There are a variety of approaches one can use. If the file has a relatively simple format then one can write a simple I/O library and use the NumPy fromfile() function and .tofile() method to read and write NumPy arrays directly 

## 6 - Use of special library functions (e.g., SciPy, Pandas, and OpenCV)