# [Indexing on ndarrays](https://numpy.org/doc/stable/user/basics.indexing.html)

## 1 - Basic indexing

### Single element indexing

In [2]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x[2]

2

In [4]:
x[-2]

8

In [5]:
x.shape

(10,)

In [6]:
x.shape = (2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
x[1, -1]

9

In [8]:
x[0][2]

2

### Slicing and striding

Note:

    NumPy slicing creates a view instead of a copy as in the case of built-in Python sequences such as string, tuple and list. Care must be taken when extracting a small portion from a large array which becomes useless after the extraction, because the small portion extracted contains a reference to the large original array whose memory will not be released until all arrays derived from it are garbage-collected. In such cases an explicit copy() is recommended.

In [9]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x[1:7:2]

array([1, 3, 5])

In [12]:
x[-5:10]

array([5, 6, 7, 8, 9])

In [13]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [14]:
# Note that :: is the same as : and means select all indices along this axis
x[5:]

array([5, 6, 7, 8, 9])

In [15]:
x[1::3]

array([1, 4, 7])

In [17]:
x2 = x[1::3] + 100
x, x2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([101, 104, 107]))

In [18]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x.shape

(2, 3, 1)

In [19]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [22]:
X = np.ones((3, 3)) + np.diag([3, 5, 10])
X

array([[ 4.,  1.,  1.],
       [ 1.,  6.,  1.],
       [ 1.,  1., 11.]])

In [25]:
X[1, 1]

6.0

In [26]:
X[:, 2]

array([ 1.,  1., 11.])

### Dimensional indexing tools

In [27]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [28]:
x[..., 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
x[:, :, 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# newaxis is an alias for None, and None can be used in place of this with the same result
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [31]:
x.shape

(2, 3, 1)

In [33]:
x[:, np.newaxis, :, :].shape, x[:, None, :, :].shape

((2, 1, 3, 1), (2, 1, 3, 1))

In [35]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [37]:
x[:, None]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [38]:
x[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

In [39]:
x[:, np.newaxis] + x[np.newaxis, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### Advanced indexing

    There are two types of advanced indexing: integer and Boolean

In [40]:
X

array([[ 4.,  1.,  1.],
       [ 1.,  6.,  1.],
       [ 1.,  1., 11.]])

In [41]:
X[0, ]

array([4., 1., 1.])

In [42]:
X[1]

array([1., 6., 1.])

In [43]:
X[1, ]

array([1., 6., 1.])

### Integer array indexing

In [44]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [45]:
x[np.array([3, 3, 1, 8])]
# If the index values are out of bounds then an IndexError is thrown

array([7, 7, 9, 2])

In [46]:
y = np.arange(35).reshape(5, 7)

In [47]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [49]:
y.shape

(5, 7)

In [48]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

array([ 0, 15, 30])

In [50]:
# example
x = np.array([[ 0,  1,  2],

              [ 3,  4,  5],

              [ 6,  7,  8],

              [ 9, 10, 11]])

In [51]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
x.shape

(4, 3)

In [53]:
rows = np.array([[0, 0],

                 [3, 3]], dtype=np.intp)

                 # 0  1  2


                 # 9 10 11

columns = np.array([[0, 2],

                    [0, 2]], dtype=np.intp)

                    # 0     2
                    # 3     5
                    # 6     8 
                    # 9     11

In [60]:
x_ex = x[rows, columns]
x_ex, x_ex.shape

(array([[ 0,  2],
        [ 9, 11]]),
 (2, 2))

In [56]:
x_ex.nonzero()

(array([0, 1, 1]), array([1, 0, 1]))

In [61]:
x_ex[x_ex.nonzero()]

array([ 2,  9, 11])

### Boolean array indexing

In [62]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [63]:
x[~np.isnan(x)]

array([1., 2., 3.])

In [64]:
x = np.array([1., -1., -2., 3])

In [65]:
x

array([ 1., -1., -2.,  3.])

In [66]:
x[x < 0] += 20 # add a constant to all negative numbers

In [67]:
x

array([ 1., 19., 18.,  3.])

In [68]:
x[x > 15]

array([19., 18.])

In [69]:
X

array([[ 4.,  1.,  1.],
       [ 1.,  6.,  1.],
       [ 1.,  1., 11.]])

In [71]:
x = np.arange(35).reshape(5, 7)

b = x > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [72]:
b.shape

(5, 7)

In [74]:
x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

### Combining advanced and basic indexing

In [75]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [76]:
y[np.array([0, 2, 4]), ]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [79]:
y[np.array([0, 2, 4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [81]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [80]:
y[:, 1:3]

array([[ 1,  2],
       [ 8,  9],
       [15, 16],
       [22, 23],
       [29, 30]])

In [82]:
y[:, 1:3][np.array([0, 2, 4]), :]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [83]:
x = np.array([[ 0,  1,  2],

              [ 3,  4,  5],

              [ 6,  7,  8],

              [ 9, 10, 11]])

x[1:2, 1:3]

array([[4, 5]])

## 2 - Assigning values to indexed arrays

In [86]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
x[2:7] = 99999999
x

array([       0,        1, 99999999, 99999999, 99999999, 99999999,
       99999999,        7,        8,        9])

In [88]:
x[2:7] = np.arange(5)
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])